/**
 * Smart Pantry AI — Shopping Routes
 * ====================================
 * Smart shopping lists powered by consumption patterns.
 */

const express = require('express');
const { Op } = require('sequelize');
const { ShoppingList, PantryItem, ConsumptionLog } = require('../models');
const { authenticate } = require('../middleware/auth');

const router = express.Router();
router.use(authenticate);

// ========================
// GET /api/shopping — Get current shopping list
// ========================
router.get('/', async (req, res) => {
  try {
    const list = await ShoppingList.findOne({
      where: { familyId: req.familyId, status: 'active' },
      order: [['createdAt', 'DESC']]
    });

    if (!list) {
      return res.json({ message: 'No active shopping list', list: null });
    }

    res.json({ list });
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch shopping list' });
  }
});

// ========================
// POST /api/shopping/generate — AI-generate a smart shopping list
// ========================
router.post('/generate', async (req, res) => {
  try {
    // 1. Get current pantry items (what we HAVE)
    const currentItems = await PantryItem.findAll({
      where: { familyId: req.familyId, status: 'active' }
    });

    // 2. Get consumption history (what we USE frequently)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const consumptionLogs = await ConsumptionLog.findAll({
      where: {
        familyId: req.familyId,
        action: 'used',
        loggedAt: { [Op.gte]: thirtyDaysAgo }
      },
      include: [{ model: PantryItem, attributes: ['name', 'category'] }]
    });

    // 3. Analyze patterns — count how often each item was used
    const usageMap = {};
    consumptionLogs.forEach(log => {
      const name = log.PantryItem?.name?.toLowerCase();
      if (name) {
        usageMap[name] = (usageMap[name] || 0) + 1;
      }
    });

    // 4. Find items that were used frequently but NOT in current pantry
    const currentNames = new Set(currentItems.map(i => i.name.toLowerCase()));
    const suggestedItems = [];

    Object.entries(usageMap)
      .sort((a, b) => b[1] - a[1]) // Sort by frequency
      .forEach(([name, count]) => {
        if (!currentNames.has(name) && count >= 2) {
          suggestedItems.push({
            name: name.charAt(0).toUpperCase() + name.slice(1),
            quantity: 1,
            unit: 'item',
            reason: `Used ${count} times in past 30 days, not in pantry`,
            autoGenerated: true,
            checked: false
          });
        }
      });

    // 5. Find items running low (quantity < 2 for countable items)
    const lowItems = currentItems
      .filter(item => parseFloat(item.quantity) <= 1 && item.status === 'active')
      .map(item => ({
        name: item.name,
        quantity: 1,
        unit: item.unit,
        reason: `Running low (${item.quantity} ${item.unit} left)`,
        autoGenerated: true,
        checked: false
      }));

    // 6. Items we already have plenty of (DON'T BUY warnings)
    const dontBuy = currentItems
      .filter(item => parseFloat(item.quantity) >= 3)
      .map(item => ({
        name: item.name,
        currentQuantity: `${item.quantity} ${item.unit}`,
        reason: `Already have ${item.quantity} ${item.unit}`
      }));

    // 7. Create/update shopping list
    const allItems = [...suggestedItems, ...lowItems];

    const list = await ShoppingList.create({
      familyId: req.familyId,
      createdBy: req.userId,
      items: allItems,
      autoGenerated: true,
      status: 'active'
    });

    res.json({
      message: `Smart shopping list generated with ${allItems.length} items`,
      list,
      dontBuy,
      insights: {
        frequentlyUsed: Object.keys(usageMap).length,
        suggestedItems: suggestedItems.length,
        lowStockItems: lowItems.length,
        dontBuyItems: dontBuy.length
      }
    });
  } catch (error) {
    console.error('Shopping list generation error:', error);
    res.status(500).json({ error: 'Failed to generate shopping list' });
  }
});

// ========================
// POST /api/shopping/add — Add item to shopping list
// ========================
router.post('/add', async (req, res) => {
  try {
    const { name, quantity, unit } = req.body;

    let list = await ShoppingList.findOne({
      where: { familyId: req.familyId, status: 'active' },
      order: [['createdAt', 'DESC']]
    });

    if (!list) {
      list = await ShoppingList.create({
        familyId: req.familyId,
        createdBy: req.userId,
        items: [],
        status: 'active'
      });
    }

    const items = [...(list.items || [])];
    items.push({
      name,
      quantity: quantity || 1,
      unit: unit || 'item',
      reason: 'Manually added',
      autoGenerated: false,
      checked: false
    });

    await list.update({ items });
    res.json({ message: 'Item added', list });
  } catch (error) {
    res.status(500).json({ error: 'Failed to add item' });
  }
});

// ========================
// PUT /api/shopping/check/:index — Toggle item checked
// ========================
router.put('/check/:index', async (req, res) => {
  try {
    const index = parseInt(req.params.index);
    const list = await ShoppingList.findOne({
      where: { familyId: req.familyId, status: 'active' },
      order: [['createdAt', 'DESC']]
    });

    if (!list || !list.items[index]) {
      return res.status(404).json({ error: 'Item not found' });
    }

    const items = [...list.items];
    items[index].checked = !items[index].checked;
    await list.update({ items });

    res.json({ message: 'Item toggled', list });
  } catch (error) {
    res.status(500).json({ error: 'Failed to update item' });
  }
});

// ========================
// PUT /api/shopping/complete — Mark list as complete
// ========================
router.put('/complete', async (req, res) => {
  try {
    const list = await ShoppingList.findOne({
      where: { familyId: req.familyId, status: 'active' },
      order: [['createdAt', 'DESC']]
    });

    if (!list) {
      return res.status(404).json({ error: 'No active shopping list' });
    }

    await list.update({ status: 'completed' });
    res.json({ message: 'Shopping trip complete! Scan your groceries to update pantry.' });
  } catch (error) {
    res.status(500).json({ error: 'Failed to complete list' });
  }
});

module.exports = router;
