/**
 * Smart Pantry AI — Database Models
 * ===================================
 * All Sequelize models for the application.
 */

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

// ========================
// USER MODEL
// ========================
const User = sequelize.define('User', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  email: {
    type: DataTypes.STRING(255),
    allowNull: false,
    unique: true,
    validate: { isEmail: true }
  },
  name: {
    type: DataTypes.STRING(100),
    allowNull: false
  },
  passwordHash: {
    type: DataTypes.TEXT,
    allowNull: false,
    field: 'password_hash'
  },
  avatarUrl: {
    type: DataTypes.TEXT,
    field: 'avatar_url'
  },
  dietaryPrefs: {
    type: DataTypes.JSONB,
    defaultValue: {
      diet: 'none',         // 'vegetarian', 'vegan', 'keto', 'none'
      allergies: [],         // ['nuts', 'dairy', 'gluten']
      cuisines: [],          // ['indian', 'italian', 'chinese']
      goalType: 'none'       // 'weight_loss', 'muscle_gain', 'none'
    },
    field: 'dietary_prefs'
  },
  familyId: {
    type: DataTypes.UUID,
    field: 'family_id',
    allowNull: true
  },
  fcmToken: {
    type: DataTypes.TEXT,
    field: 'fcm_token'
  }
}, {
  tableName: 'users',
  underscored: true
});

// ========================
// FAMILY MODEL
// ========================
const Family = sequelize.define('Family', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  name: {
    type: DataTypes.STRING(100),
    allowNull: false
  },
  inviteCode: {
    type: DataTypes.STRING(8),
    unique: true,
    field: 'invite_code'
  },
  createdBy: {
    type: DataTypes.UUID,
    field: 'created_by'
  }
}, {
  tableName: 'families',
  underscored: true
});

// ========================
// PANTRY ITEM MODEL
// ========================
const PantryItem = sequelize.define('PantryItem', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  familyId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'family_id'
  },
  addedBy: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'added_by'
  },
  name: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  category: {
    type: DataTypes.STRING(50),
    defaultValue: 'other'
    // Categories: dairy, meat, vegetables, fruits, grains, 
    // beverages, snacks, condiments, frozen, other
  },
  quantity: {
    type: DataTypes.DECIMAL(10, 2),
    defaultValue: 1
  },
  unit: {
    type: DataTypes.STRING(20),
    defaultValue: 'item'
    // Units: item, lb, oz, gal, ct, bag, box, can, bottle
  },
  purchaseDate: {
    type: DataTypes.DATEONLY,
    defaultValue: DataTypes.NOW,
    field: 'purchase_date'
  },
  expiryDate: {
    type: DataTypes.DATEONLY,
    allowNull: true,
    field: 'expiry_date'
  },
  imageUrl: {
    type: DataTypes.TEXT,
    field: 'image_url'
  },
  status: {
    type: DataTypes.ENUM('active', 'used', 'expired', 'wasted'),
    defaultValue: 'active'
  },
  confidence: {
    type: DataTypes.FLOAT,
    defaultValue: 1.0
    // AI detection confidence score (0-1)
  },
  scanSessionId: {
    type: DataTypes.UUID,
    field: 'scan_session_id'
  }
}, {
  tableName: 'pantry_items',
  underscored: true
});

// ========================
// SCAN SESSION MODEL
// ========================
const ScanSession = sequelize.define('ScanSession', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  userId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'user_id'
  },
  familyId: {
    type: DataTypes.UUID,
    field: 'family_id'
  },
  scanType: {
    type: DataTypes.ENUM('photo', 'receipt'),
    allowNull: false,
    field: 'scan_type'
  },
  imageUrl: {
    type: DataTypes.TEXT,
    field: 'image_url'
  },
  rawAiResponse: {
    type: DataTypes.JSONB,
    field: 'raw_ai_response'
  },
  itemCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'item_count'
  }
}, {
  tableName: 'scan_sessions',
  underscored: true
});

// ========================
// SHOPPING LIST MODEL
// ========================
const ShoppingList = sequelize.define('ShoppingList', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  familyId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'family_id'
  },
  createdBy: {
    type: DataTypes.UUID,
    field: 'created_by'
  },
  items: {
    type: DataTypes.JSONB,
    defaultValue: []
    // [{ name, quantity, unit, reason, autoGenerated, checked }]
  },
  status: {
    type: DataTypes.ENUM('active', 'completed'),
    defaultValue: 'active'
  },
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'auto_generated'
  }
}, {
  tableName: 'shopping_lists',
  underscored: true
});

// ========================
// CONSUMPTION LOG MODEL
// ========================
const ConsumptionLog = sequelize.define('ConsumptionLog', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  pantryItemId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'pantry_item_id'
  },
  familyId: {
    type: DataTypes.UUID,
    field: 'family_id'
  },
  action: {
    type: DataTypes.ENUM('used', 'wasted', 'expired'),
    allowNull: false
  },
  quantity: {
    type: DataTypes.DECIMAL(10, 2)
  },
  loggedAt: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    field: 'logged_at'
  }
}, {
  tableName: 'consumption_log',
  underscored: true
});

// ========================
// ASSOCIATIONS
// ========================
Family.hasMany(User, { foreignKey: 'familyId' });
User.belongsTo(Family, { foreignKey: 'familyId' });

Family.hasMany(PantryItem, { foreignKey: 'familyId' });
PantryItem.belongsTo(Family, { foreignKey: 'familyId' });

User.hasMany(PantryItem, { foreignKey: 'addedBy' });
PantryItem.belongsTo(User, { foreignKey: 'addedBy', as: 'addedByUser' });

User.hasMany(ScanSession, { foreignKey: 'userId' });
ScanSession.belongsTo(User, { foreignKey: 'userId' });

ScanSession.hasMany(PantryItem, { foreignKey: 'scanSessionId' });
PantryItem.belongsTo(ScanSession, { foreignKey: 'scanSessionId' });

PantryItem.hasMany(ConsumptionLog, { foreignKey: 'pantryItemId' });
ConsumptionLog.belongsTo(PantryItem, { foreignKey: 'pantryItemId' });

module.exports = {
  User,
  Family,
  PantryItem,
  ScanSession,
  ShoppingList,
  ConsumptionLog
};
